    apiVersion: v1
    kind: Service
    metadata:
      name: patient-service
    spec:
      selector:
        app: patient-service
      ports:
        - protocol: TCP
          port: 80
          targetPort: 3000 # The port your Node.js app listens on
      type: LoadBalancer # For external access