    apiVersion: v1
    kind: Service
    metadata:
      name: appointment-service
    spec:
      selector:
        app: appointment-service
      ports:
        - protocol: TCP
          port: 80
          targetPort: 3000 # The port your Node.js app listens on
      type: LoadBalancer # For external access